Numpy Assignment 1

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("a) Reversed:", arr[::-1])


a) Reversed: [5 4 6 3 2 1]


In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("b) Flatten (flatten):", array1.flatten())
print("   Flatten (ravel):", array1.ravel())

b) Flatten (flatten): [1 2 3 2 4 5 1 2 3]
   Flatten (ravel): [1 2 3 2 4 5 1 2 3]


In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("c) Arrays equal:", np.array_equal(arr1, arr2))

c) Arrays equal: True


In [5]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
val_x = np.bincount(x).argmax()
val_y = np.bincount(y).argmax()
print("d) x: most frequent =", val_x, "at", np.where(x == val_x)[0])
print("   y: most frequent =", val_y, "at", np.where(y == val_y)[0])


d) x: most frequent = 1 at [0 5 7 8 9]
   y: most frequent = 1 at [0 1 2]


In [6]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("e) Total sum:", gfg.sum())
print("   Row-wise:", gfg.sum(axis=1))
print("   Column-wise:", gfg.sum(axis=0))

e) Total sum: 45
   Row-wise: [[14]
 [16]
 [15]]
   Column-wise: [[20  9 16]]


In [7]:
n = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("f) Diagonal sum:", np.trace(n))
print("   Eigen values:", np.linalg.eigvals(n))
print("   Inverse:\n", np.linalg.inv(n))
print("   Determinant:", np.linalg.det(n))


f) Diagonal sum: 176
   Eigen values: [98.16835147 28.097044   49.73460452]
   Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
   Determinant: 137180.0000000001


In [8]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print("g) i. Dot product:\n", np.dot(p1, q1))

g) i. Dot product:
 [[16 19]
 [26 31]]


In [9]:
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print("   ii. Dot product:\n", np.dot(p2, q2))


   ii. Dot product:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]


In [10]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("h) Inner:\n", np.inner(x, y))
print("   Outer:\n", np.outer(x, y))
print("   Cartesian product:\n", np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2))

h) Inner:
 [[17 52]
 [13 62]]
   Outer:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
   Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [11]:


array = np.array([[1, -2, 3], [-4, 5, -6]])

print(np.abs(array))

print(np.percentile(array, 25))
print(np.percentile(array, 50))
print(np.percentile(array, 75))

print(np.percentile(array, 25, axis=0))
print(np.percentile(array, 50, axis=0))
print(np.percentile(array, 75, axis=0))

print(np.percentile(array, 25, axis=1))
print(np.percentile(array, 50, axis=1))
print(np.percentile(array, 75, axis=1))

print(np.mean(array))
print(np.median(array))
print(np.std(array))

print(np.mean(array, axis=0))
print(np.median(array, axis=0))
print(np.std(array, axis=0))

print(np.mean(array, axis=1))
print(np.median(array, axis=1))
print(np.std(array, axis=1))

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))


[[1 2 3]
 [4 5 6]]
-3.5
-0.5
2.5
[-2.75 -0.25 -3.75]
[-1.5  1.5 -1.5]
[-0.25  3.25  0.75]
[-0.5 -5. ]
[ 1. -4.]
[2.  0.5]
-0.5
-0.5
3.8622100754188224
[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]
[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]
[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [12]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

print(np.sort(array))
print(np.argsort(array))
print(np.sort(array)[:4])
print(np.sort(array)[-5:])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [13]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

print(array[array == array.astype(int)])
print(array[array != array.astype(int)])

[1. 2. 3. 2.]
[1.2 2.2]


In [26]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        np.savetxt("grayscale_image.txt", arr, fmt='%d')
        print(f"{path} is a Grayscale image. Saved as 'grayscale_image.txt'")
    else:
        reshaped = arr.reshape(-1, arr.shape[-1])
        np.savetxt("rgb_image.txt", reshaped, fmt='%d')
        print(f"{path} is an RGB image. Saved as 'rgb_image.txt'")

img_to_array("gray_image.jpg")
img_to_array("color_image.jpg")

print("\n--- Loaded from grayscale_image.txt ---")
gray = np.loadtxt("grayscale_image.txt", dtype=int)
print(gray)

print("\n--- Loaded from rgb_image.txt ---")
rgb = np.loadtxt("rgb_image.txt", dtype=int).reshape(-1, 3)
print(rgb)


gray_image.jpg is a Grayscale image. Saved as 'grayscale_image.txt'
color_image.jpg is an RGB image. Saved as 'rgb_image.txt'

--- Loaded from grayscale_image.txt ---
[[ 0  0  0 ... 48 48 49]
 [ 0  0  0 ... 48 49 49]
 [ 0  0  1 ... 49 49 50]
 ...
 [48 48 49 ... 96 97 97]
 [48 49 49 ... 97 97 97]
 [49 49 50 ... 97 97 98]]

--- Loaded from rgb_image.txt ---
[[  1   1   1]
 [  1   1   1]
 [  3   1   2]
 ...
 [193 197 196]
 [196 198 197]
 [197 199 198]]
